# Generated by Django 4.0 on 2022-08-31 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_image',
        ),
        migrations.AddField(
            model_name='post',
            name='post_media',
            field=models.FileField(blank=True, null=True, upload_to='post_media'),
        ),
    ]
