# Generated by Django 4.0 on 2022-09-10 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userblock',
        ),
    ]
