# Generated by Django 4.0 on 2022-08-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='up_vote_by',
            new_name='vote_by',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='down_vote_by',
        ),
        migrations.AddField(
            model_name='vote',
            name='type',
            field=models.BooleanField(null=True),
        ),
    ]
