# Generated by Django 4.0 on 2022-08-10 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('votes', '0002_rename_up_vote_by_vote_vote_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='vote_by',
            new_name='up_vote_by',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='type',
        ),
        migrations.AddField(
            model_name='vote',
            name='down_vote_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='down_vote_user', to='users.account'),
        ),
    ]
