# Generated by Django 4.0 on 2022-09-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_chat_chats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chats',
            old_name='name',
            new_name='room_name',
        ),
    ]
