# Generated by Django 4.0 on 2022-09-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_rename_chat_messages_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
