# Generated by Django 4.0 on 2022-08-25 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='users.account')),
                ('request_from', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='request_from', to='users.account')),
                ('request_to', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='request_to', to='users.account')),
            ],
        ),
    ]
