# Generated by Django 4.0 on 2022-08-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
