# Generated by Django 4.0 on 2022-08-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
