# Generated by Django 4.0 on 2022-09-10 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockUser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userblock',
            name='status',
        ),
    ]
