# Generated by Django 4.0 on 2022-09-11 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_userblock'),
        ('blockUser', '0002_remove_userblock_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblock',
            name='blocked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked', to='users.account'),
        ),
    ]
